##################################
# Makefile autogenerated by pgcc #
##################################

HOME=$(shell echo $$HOME)
PROCESSES_BIN:=$(addprefix processes/, $(PROCESSES))

INCLUDES:=$(HOME)/.pgcc/include /usr/include/pgcc
INCLUDES:=$(addprefix -I, $(INCLUDES))



all: $(PROCESSES_BIN)


processes/%: src/%.cpp
	@mkdir -p processes/
	g++ -o $@ $(INCLUDES) $<
