##################################
# Makefile autogenerated by pgcc #
##################################

PROCESSES_BIN:=$(addprefix processes/, $(PROCESSES))

INCLUDES:=$(shell ~/.pgcc/pgcc-include-path)
INCLUDES:=$(addprefix -I, $(INCLUDES))



all: $(PROCESSES_BIN)


processes/%: src/%.cpp
	@mkdir -p processes/
	g++ -o $@ $< $(INCLUDES)
